name: Continuous Delivery - test
on:
  push:
    branches:
      - main

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Teste Continuous Delivery
        uses: actions/upload-artifact@v4
        with:
          name: teste
          path: |
            '**.py'
            README.md