name: Continuous Delivery - test
on:
  push:
    branches:
      - main

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Teste Continuous Delivery
        uses: actions/upload-artifact@v4
        with:
          name: teste
          path: |
            **.py
            README.md
            
  deploy:
    runs-on: ubuntu-latest
    needs: deliver
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: teste
      - name: Display structure of downloaded files
        run: ls -R