name: Discord
on:
   - push

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - name: Run Discord Webhook
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          template: "avatar-with-link"
          include-extras: true